### ISSUE TITLE
CMMSW version issue

### ISSUE THREAD

**Issue by Oguz-Guzel** [kjaffel/CPEanalyzer#2]
Hi, I'm having this error when working with `CMSSW_11_3_0`,

```
Error in <TChain::LoadTree>: Cannot find tree with name anResol/reso in file mytestDIR/outputs/SiStripCalMinBias_Express_Run2018D.root
Error in <TChain::LoadTree>: Cannot find tree with name anResol/reso in file mytestDIR/outputs/SiStripCalMinBias_Express_Run2018D.root
Traceback (most recent call last):
  File "postprocessing.py", line 215, in <module>
    runPlotter(workdir=options.workdir, run=options.run)
  File "postprocessing.py", line 190, in runPlotter
    ROOT.Resolutions(units[k2], compaigns[run], rf, rp, cltrk_w, cluster_cut, False)
cppyy.gbl.std.runtime_error: void ::Resolutions(const int& Unit_Int, const int& UL, const string& InputFileString, const string& InputFilePath, const string& ClusterTrackWidth, const string& cluster_cut, const bool& DOESEXIST) =>
    runtime_error: GetBranchNames: error in opening the tree anResol/reso
```

But `CMSSW 11_2_2_patch1` works quite well. Do you have an idea?

**Comment by kjaffel** [comment]
Hi Oguz, 
Your issue is in the post-processing step. So something went wrong in the generation of ``SiStripCalMinBias_Express_Run2018D.root`` file. Worth looking at the log of the slurm job.
